name: "Build, Tag and Release"

on:
  push:
    branches:
      - "**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0' # The Go version to download (if necessary) and use.
      - run: go version
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
      - name: Build and Test
        run: make test

  tag-and-release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [build-and-test]
    steps:
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
